services:
  ml-server:
    image: dhruv2k3/basal-ml-server:latest
    container_name: ml-server
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - basal-net
networks:
  basal-net:
    driver: bridge