name: biasbreaker

# --- Local Image Context ---

# services:
#   ml-server:
#     container_name: ml-server
#     build: .
#     ports:
#       - "8001:8001"
#     restart: always


# --- hub.docker Image Context ---

services:
  ml-server:
    container_name: ml-server
    image: dhruv2k3/biasbreaker-ml-server:latest
    pull_policy: always
    ports:
      - "8001:8001"
    restart: always
